### ISSUE TITLE
About DOOB'evaluation code

### ISSUE THREAD

**Issue by buptlr** [GuoxiaWang/DOOBNet#2]
Hi, Guoxia Wang. I tried to use your _DOOBNet/doobscripts/evaluation/EvaluateOcc.m_ to evaluate occ edge results. But I don't understand the content of _edge_maps_, which is in _EvaluateBoundary.m_
```
resfile = fullfile(resPath, [imglist{ires}, '.mat']);
edge_maps = load(resfile);
edge_maps = edge_maps.edge_ori;
res_img = zeros([size(edge_maps.edge), 2], 'single');
res_img(:,:,1) = edge_maps.edge;
res_img(:,:,2) = edge_maps.ori;
```
Can you please tell what is included in _edge_maps,_ and besides, whether the _edge_maps.edge_ and _edge_maps.ori_ are the original result of the test, without any processing(such as NMS)?
Thank you very much!

**Comment by GuoxiaWang** [comment]
`edge_maps ` is the predicted .mat results, which contains two maps (the one  is  object boundary map and the other one  is occlusion orientation map)

Here  is the python save code:
```
    edge_ori = {}
    edge_ori['edge'] = edgemap
    edge_ori['ori'] = orimap
    sio.savemat( 'xxx.mat', {'edge_ori':edge_ori})
```

**Comment by buptlr** [comment]
Thank you! I get it!

**Comment by praful1993** [comment]
You have got the edge map from DooBNet. Then how  you  got the occlusion orientation map from edge map ???
Can you please explain me.
