### ISSUE TITLE
Is class_balanced_sigmoid_cross_entropy_attention_loss_layer.cu the GPU version of HED?

### ISSUE THREAD

**Issue by xjock** [GuoxiaWang/DOOBNet#3]
I appreciate it.

**Comment by GuoxiaWang** [comment]
@xjock 

No, Attention Loss was proposed in [DOOBNet](xiv.org/abs/1806.03772).

But when beta = 1, AL is equivalent to CCE in HED.

**Comment by xjock** [comment]
Thanks! I will read your paper carefully. Great job!
