### ISSUE TITLE
Offer edge_ori maps of previous methods for evaluation

### ISSUE THREAD

**Issue by tim885** [GuoxiaWang/DOOBNet#8]
Hi guoxia, 

Thanks a lot for your evaluation code, it's very useful! Btw, can you kindly offer a link to edge_ori predictions of previous methods? When I try to run OccCompCurvesPlot.m, I can't find predictions of previous methods. I think the offered source will be a good contribution to the community. 

Thank you by advance!

**Comment by GuoxiaWang** [comment]
@tim885 Sorry, I read this issue until now. The comparison files of previous methods can be find in [Eval folder](https://github.com/GuoxiaWang/DOOBNet/tree/master/eval). Hope to help you!

**Comment by tim885** [comment]
Thanks a lot!
